settings:
  layouts_enable: 1
  enable_extensions: 0
  enable_responsive_menus: 0
  enable_fonts: 0
  enable_titles: 0
  enable_images: 0
  enable_touch_icons: 0
  enable_libraries: 0
  enable_classitis: 0
  enable_custom_css: 0
  enable_markup_overrides: 0
  enable_devel: 0
  enable_legacy_browsers: 0
  suggestions:
    page: page
  breakpoint_group_layout: at_core.simple
  max_width_enable: 0
  max_width_value: ''
  max_width_unit: em
  enable_backups: 0
  page_Mobile-tablet_messages: ''
  page_Mobile-tablet_header: ''
  page_Mobile-tablet_navbar: ''
  page_Mobile-tablet_highlighted: ''
  page_Mobile-tablet_main: ''
  page_Mobile-tablet_footer: ''
  page_Tablet-isolate_messages: ''
  page_Tablet-isolate_header: twocol-6-6
  page_Tablet-isolate_navbar: ''
  page_Tablet-isolate_highlighted: ''
  page_Tablet-isolate_main: threecol-split-row-12--6-6
  page_Tablet-isolate_footer: ''
  page_Widescreen_messages: ''
  page_Widescreen_header: twocol-6-6
  page_Widescreen_navbar: ''
  page_Widescreen_highlighted: ''
  page_Widescreen_main: threecol-source-ordered-3-6-3
  page_Widescreen_footer: ''
  responsive_menu_region: navbar
  responsive_menu_breakpoint_group: at_core.simple
  responsive_menu_default_style: slidedown
  responsive_menu_default_offcanvas_position: offcanvas-left
  responsive_menu_default_tiles_count: two
  responsive_menu_default_tiles_submenus: 0
  responsive_menu_responsive_style: dropmenu
  responsive_menu_responsive_breakpoint: 'all and (min-width: 65em)'
  responsive_menu_responsive_offcanvas_position: offcanvas-left
  responsive_menu_responsive_tiles_count: two
  responsive_menu_responsive_tiles_submenus: 0
  icon_path_default: images/touch-icons/default-60x60.png
  apple_touch_icon_path_ipad: images/touch-icons/ipad-standard-76x76.png
  apple_touch_icon_path_iphone_retina: images/touch-icons/iphone-retina-120x120.png
  apple_touch_icon_path_ipad_retina: images/touch-icons/ipad-retina-152x152.png
  apple_touch_icon_precomposed: 0
  generated_files_path: themes/THEMENAME/styles/css/generated
  extensions_form_open: 0
  layouts_form_open: 0
features:
  logo: 1
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 1
  path: ''
