shortcut_module_link: '0'
settings:
  layouts_enable: 1
  layout_master_layout: univer
  layouts_no_mq_metro: 1
  layouts_no_mq_publisher: 1
  layouts_no_mq_univer: 1
  show_page_suggestions: 0
  disable_backups: 0
  show_window_size: 0
  livereload: 0
  livereload_snippet: ''
  devel_layout: 0
  nuke_toolbar: 0
  libraries_enable: 0
  library_modernizr: 0
  library_scalefix: 0
  drupal_core_drupal_debounce: 0
  drupal_core_domready: 0
  drupal_core_jquery: 0
  drupal_core_jquery_once: 0
  drupal_core_jquery_form: 0
  drupal_core_jquery_bbq: 0
  drupal_core_matchmedia: 0
  drupal_core_jquery_ui_core: 0
  drupal_core_jquery_ui_accordion: 0
  drupal_core_jquery_ui_autocomplete: 0
  drupal_core_jquery_ui_button: 0
  drupal_core_jquery_ui_datepicker: 0
  drupal_core_jquery_ui_dialog: 0
  drupal_core_jquery_ui_draggable: 0
  drupal_core_jquery_ui_droppable: 0
  drupal_core_jquery_ui_menu: 0
  drupal_core_jquery_ui_mouse: 0
  drupal_core_jquery_ui_position: 0
  drupal_core_jquery_ui_progressbar: 0
  drupal_core_jquery_ui_resizable: 0
  drupal_core_jquery_ui_selectable: 0
  drupal_core_jquery_ui_slider: 0
  drupal_core_jquery_ui_sortable: 0
  drupal_core_jquery_ui_spinner: 0
  drupal_core_jquery_ui_tabs: 0
  drupal_core_jquery_ui_tooltip: 0
  drupal_core_jquery_ui_widget: 0
  drupal_core_jquery_effects_core: 0
  drupal_core_jquery_effects_blind: 0
  drupal_core_jquery_effects_bounce: 0
  drupal_core_jquery_effects_clip: 0
  drupal_core_jquery_effects_drop: 0
  drupal_core_jquery_effects_explode: 0
  drupal_core_jquery_effects_fade: 0
  drupal_core_jquery_effects_fold: 0
  drupal_core_jquery_effects_highlight: 0
  drupal_core_jquery_effects_pulsate: 0
  drupal_core_jquery_effects_scale: 0
  drupal_core_jquery_effects_shake: 0
  drupal_core_jquery_effects_slide: 0
  drupal_core_jquery_effects_transfer: 0
  drupal_core_jquery_ui_touch-punch: 0
  drupal_core_underscore: 0
  drupal_core_backbone: 0
  template_suggestion_page: univer