shortcut_module_link: 0
settings:
  layouts_enable: 1
  template_suggestion_page: univer
  master_layout: site-builder
  selected_layout_minima: univer
  max_width_enable: 0
  max_width_value: ''
  max_width_unit: ''
  layouts_no_mq_metro: 1
  layouts_no_mq_publisher: 1
  layouts_no_mq_univer: 1
  enable_backups: 1
  enable_extensions: 0
  enable_fonts: 0
  enable_titles: 0
  enable_images: 0
  enable_touch_icons: 0
  enable_libraries: 0
  enable_custom_css: 0
  enable_markup_overrides: 0
  show_page_suggestions: 0
  show_window_size: 0
  livereload: 0
  livereload_snippet: ''
  devel_layout: 0
  nuke_toolbar: 0
  default_layout_provider: at_standard
  template_suggestion_provider_page: at_standard
  template_suggestion_plugin_page: site-builder
features:
  logo: 1
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 1
  path: ''