id: at_standard.branding
weight: 0
status: 1
langcode: en
region: header_second
plugin: system_branding_block
settings:
  label: 'Page Site Branding'
  module: system
  label_display: 0
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: { }
  node_type:
    types:
      article: 0
      page: 0
