id: at_standard_powered
weight: -3
status: true
langcode: en
theme: at_standard
region: footer
plugin: system_powered_by_block
settings:
  label: 'Powered by Drupal'
  module: system
  label_display: '0'
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
