id: at_standard_tools
weight: 0
status: true
langcode: en
theme: at_standard
region: sidebar_first
plugin: 'system_menu_block:tools'
settings:
  label: 'Tools'
  module: system
  label_display: visible
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: 0
      page: 0
  visibility__active_tab: edit-visibility-path
