id: at_standard_help
weight: 0
status: true
langcode: en
theme: at_standard
region: messages
plugin: system_help_block
settings:
  label: 'System Help'
  module: system
  label_display: '0'
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
