id: at_standard_content
weight: -3
status: true
langcode: en
theme: at_standard
region: content
plugin: system_main_block
settings:
  label: 'Main page content'
  module: system
  label_display: 0
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: 0
      page: 0
  visibility__active_tab: edit-visibility-path
