id: atblockssitebranding
weight: -5
status: true
langcode: en
theme: at_standard
region: header_second
plugin: atblocks_branding_block
settings:
  logo: 1
  sitename: 1
  siteslogan: 1
  label: 'Atblocks Site Branding'
  module: at_blocks
  label_display: '0'
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
