id: atblockspagetitle
weight: -4
status: true
langcode: en
theme: at_minimal
region: content
plugin: atblocks_pagetitle_block
settings:
  label: 'Atblocks Page Title'
  module: at_blocks
  label_display: '0'
  cache: -1
visibility:
  path:
    visibility: 0
    pages: "<front>\r\nnode*"
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
